export const languages = [
  { code: "en", name: "English" },
  { code: "zh-CN", name: "简体中文" },
  { code: "es", name: "Español" },
  { code: "pt", name: "Português" },
  { code: "ko", name: "한국어" },
  { code: "ja", name: "日本語" },
  { code: "zh-TW", name: "繁体中文" },
  { code: "de", name: "Deutsch" },
  { code: "fr", name: "Français" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "ar", name: "العربية" },
  { code: "nl", name: "Nederlands" },
  { code: "pl", name: "Polski" },
];
const allLanguages = [
  { code: "en", name: "English" },
  { code: "zh-CN", name: "简体中文" },
  { code: "es", name: "Español" },
  { code: "hi", name: "हिन्दी" },
  { code: "ar", name: "العربية" },
  { code: "fr", name: "Français" },
  { code: "bn", name: "বাংলা" },
  { code: "ru", name: "Русский" },
  { code: "pt", name: "Português" },
  { code: "pt-BR", name: "Português do Brasil" },
  { code: "id", name: "Bahasa Indonesia" },
  { code: "de", name: "Deutsch" },
  { code: "ja", name: "日本語" },
  { code: "tr", name: "Türkçe" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "th", name: "ไทย" },
  { code: "ko", name: "한국어" },
  { code: "it", name: "Italiano" },
  { code: "pl", name: "Polski" },
  { code: "uk", name: "Українська" },
  { code: "nl", name: "Nederlands" },
  { code: "ms", name: "Bahasa Melayu" },
  { code: "zh-TW", name: "繁体中文" },
  { code: "ro", name: "Română" },
  { code: "el", name: "Ελληνικά" },
  { code: "cs", name: "Čeština" },
  { code: "sv", name: "Svenska" },
  { code: "hu", name: "Magyar" },
  { code: "bg", name: "Български" },
  { code: "he", name: "עברית" },
  { code: "da", name: "Dansk" },
  { code: "fi", name: "Suomi" },
  { code: "sk", name: "Slovenčina" },
  { code: "no", name: "Norsk" },
  { code: "hr", name: "Hrvatski" },
  { code: "lt", name: "Lietuvių" },
  { code: "sl", name: "Slovenščina" },
  { code: "lv", name: "Latviešu" },
  { code: "et", name: "Eesti" }
];
export const defaultLocale = "en";
export const supportedLocales = languages.map((lang) => lang.code);

